apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kitties.substrate.rs
  annotations:
  # traefik.ingress.kubernetes.io/redirect-entry-point: https
  # kubernetes.io/ingress.class: traefik
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/acme-challenge-type: http01
spec:
  rules:
  - host: kitties.substrate.rs
    http:
      paths:
      - path: /
        backend:
          serviceName: kitties
          servicePort: 80
  tls:
  - hosts:
    - kitties.substrate.rs
    secretName: kitties.substrate.rs
