apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kitties
  name: kitties
data:
  Caddyfile: |-
    {
      http_port 80
      debug
      admin off
    }

    :80 {
      route /* {
        file_server {
          root /srv/build
        }
      }
      route /rpc/ws {
        reverse_proxy http://localhost:9944 {
          header_up Host {http.reverse_proxy.upstream.hostport}
        }
      }
    }

